# Generated by Django 3.1 on 2024-08-09 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_product_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_variation',
            new_name='variations',
        ),
    ]
